### 使用try....catch捕获异常
1. 如果java运行时环境收到了异常信息时，找不到处理该异常的catch块，则终止运行；
2. catch（）可以包含多种异常，异常之间通过竖线|分隔；多种异常下，异常变量默认带final修饰
```
try {
                    
}catch (IndexOutOfBoundsException | NumberFormatException | NullPointerException e){
    //此时变量e默认有final修饰
}
```
3. 有多个catch块时，当进入到一个catch块之后就不会再向下面的catch块代码执行；
4. finally用于最后进行资源关闭；
5. try后可以用（）来对一些资源进行声明和初始化，**最后一个语句不需要加分号**；如：`try(String src = "1")`

### 异常的分类
1. Throwable是异常的父类，其下异常分为：Exception（异常）和Error（错误）两大类；
#### Error错误
Error错误一般指与虚拟机相关的问题，如系统崩溃、虚拟机错误、动态连接失败等；**这种错误一般引用无法解决，所以不要捕抓**
#### Exception（异常）
1. 常见的异常：
    >`IndexOutOfBoundsException`:数组下标越界；
    >`NumberFormatException`:输入数字类型格式异常；
    >`NullPointerException`:空指针异常；
    >`ArithmeticException`:除0异常；
2. 还分成`Runtime`异常以及`Checked`异常
    * `Runtime`异常：所有RuntimeException的子类；
    * `Checked`异常：java程序可修复的异常，所以**必须要显示处理checked异常**,不然无法通过编译；
    * 区别：`Runtime`异常可以不需要使用try...catch捕抓或者使用throws抛出异常，而`Checked`异常需要；
    * 相同：两种异常产生后，同样会抛出给调用者，即抛出到jvm会终止程序；
3. Exception（异常）常用方法：
    >getMessage():返回详细描述字符串；
    >printStackTrace()：输出错误信息栈；
    >getStackTrace():返回错误信息栈；

### 关闭资源
1. 可以在try语句中声明和初始化**可关闭**资源（指实现了AutoCloseable接口或者Closeable接口），并在结束之后自动关闭；
```
try(
        FileInputStream inputStream = new FileInputStream(new File("a.txt"));
        PrintStream ps = new PrintStream(new FileOutputStream("a.txt"))
) {
    //在括号中可使用声明的对象
    ps.println("a");
} catch (Exception e) {
    e.printStackTrace();
}
```
2. java7之后，几乎所有资源类（IO类、JDBC的connection/Statement等接口）都进行了改写，实现了AutoCloseable或Closeable接口；

### Throws抛出异常
1. JVM处理异常的方法：打印异常跟踪栈信息，并终止程序运行；